# Generated by Django 3.2.14 on 2023-01-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaginglivedata',
            name='degree1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
