# Generated by Django 3.2.14 on 2023-01-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_packaginglivedata_degree1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedata',
            name='mac_addr',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
