# Generated by Django 3.2.14 on 2023-06-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0003_aggregatedata_mac_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoppageTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mac_addr', models.CharField(max_length=50)),
                ('dur_start', models.BigIntegerField()),
                ('dur_end', models.BigIntegerField()),
                ('dur_stoppage', models.BigIntegerField()),
                ('section', models.CharField(max_length=50)),
            ],
        ),
    ]
