# Generated by Django 3.2.14 on 2022-08-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_auto_20220803_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='position',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='position',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
