# Generated by Django 3.2.14 on 2022-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='flag_on',
            field=models.CharField(default='off', max_length=5),
        ),
    ]
