# Generated by Django 3.2.14 on 2022-10-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_rotation_flag_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
    ]
