# Generated by Django 3.2.14 on 2023-04-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_onehourtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifteenminflow',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fiveminflow',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onehourflow',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oneminflow',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thirtyminflow',
            name='sendDataTime',
            field=models.DateTimeField(),
        ),
    ]
