# Generated by Django 3.2.14 on 2023-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0021_auto_20230429_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='flag_on',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
