# Generated by Django 3.2.14 on 2023-05-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0022_alter_rotation_flag_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('position', models.CharField(default=None, max_length=10, null=True)),
                ('sendDataTime', models.DateTimeField(auto_now_add=True)),
                ('data', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('type_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.typedata')),
            ],
        ),
    ]
