# Generated by Django 3.2.14 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0024_auto_20230913_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifteenminflow',
            name='sendDataTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fiveminflow',
            name='sendDataTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='onehourflow',
            name='sendDataTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='onehourtest',
            name='sendDataTime',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='oneminflow',
            name='sendDataTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='sendDataTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='thirtyminflow',
            name='sendDataTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='fifteenminflow',
            index=models.Index(fields=['sendDataTime'], name='logs_fiftee_sendDat_46bce4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiveminflow',
            index=models.Index(fields=['sendDataTime'], name='logs_fivemi_sendDat_b8f555_idx'),
        ),
        migrations.AddIndex(
            model_name='onehourflow',
            index=models.Index(fields=['sendDataTime'], name='logs_onehou_sendDat_d2d7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='onehourtest',
            index=models.Index(fields=['sendDataTime'], name='logs_onehou_sendDat_205eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='oneminflow',
            index=models.Index(fields=['sendDataTime'], name='logs_onemin_sendDat_0bdb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='rotation',
            index=models.Index(fields=['sendDataTime'], name='logs_rotati_sendDat_fd11e2_idx'),
        ),
        migrations.AddIndex(
            model_name='thirtyminflow',
            index=models.Index(fields=['sendDataTime'], name='logs_thirty_sendDat_361481_idx'),
        ),
    ]
