# Generated by Django 3.2.14 on 2024-05-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0025_auto_20230913_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fifteenminflow',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='fiveminflow',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='lastoffline',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='onehourflow',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='onehourtest',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='oneminflow',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='thirtyminflow',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
    ]
