# Generated by Django 3.2.14 on 2024-05-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0026_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifteenminflow',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='fiveminflow',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='lastoffline',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='livedata',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='logdata',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='onehourflow',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='oneminflow',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AddField(
            model_name='thirtyminflow',
            name='pin1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
        migrations.AlterField(
            model_name='onehourtest',
            name='pin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.pin'),
        ),
    ]
