# Generated by Django 3.2.14 on 2024-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0027_chargecounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecounts',
            name='start_between_charge',
            field=models.IntegerField(db_index=True),
        ),
    ]
