# Generated by Django 3.2.14 on 2024-05-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0028_auto_20240528_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifteenminflow',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='fiveminflow',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='lastoffline',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='livedata',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='logdata',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='onehourflow',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='oneminflow',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='rotation',
            old_name='pin1',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='thirtyminflow',
            old_name='pin1',
            new_name='pin',
        ),
    ]
