# Generated by Django 3.2.14 on 2024-06-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0028_alter_chargecounts_start_between_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargecounts',
            options={'verbose_name': 'ChargeCount', 'verbose_name_plural': 'ChargeCounts'},
        ),
        migrations.RenameField(
            model_name='chargecounts',
            old_name='start_between_charge',
            new_name='stop_between_charge',
        ),
    ]
